export const  CRATE_ORDER_SUCCESS="CRATE_ORDER_SUCCESS"
export const  CRATE_ORDER_REQUEST="CRATE_ORDER_REQUEST"
export const CRATE_ORDER_FAIL="CRATE_ORDER_FAIL"


export const CLEAR_ERROR ="CLEAR_ERROR"